# Generated by Django 3.2.12 on 2022-02-11 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20220210_1541'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profile_img',
            new_name='profile_image',
        ),
    ]
